version: "3.9"

services:
  db:
    image: postgres:15
    container_name: banking-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
    volumes:
      - banking_pgdata:/var/lib/postgresql/data

volumes:
  banking_pgdata:
